/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-121682-g7435a3180d-20251107"
#endif /* AVUTIL_FFVERSION_H */
